//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileDiggerTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="ServiceReference1.IFileDigger")]
    public interface IFileDigger {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/addPeer", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/addPeerResponse")]
        void addPeer(string peer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/deletePeer", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/deletePeerResponse")]
        void deletePeer(string peer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/findPeers", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/findPeersResponse")]
        string[] findPeers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/addFolder", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/addFolderResponse")]
        void addFolder(string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/deleteSharedFolder", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/deleteSharedFolderResponse")]
        void deleteSharedFolder(string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/findFile", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/findFileResponse")]
        string[] findFile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/findSharedFolders", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/findSharedFoldersResponse")]
        string[] findSharedFolders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/fetchFile", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/fetchFileResponse")]
        byte[] fetchFile(string fullName, int i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileDiggerChannel : FileDiggerTest.ServiceReference1.IFileDigger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileDiggerClient : System.ServiceModel.ClientBase<FileDiggerTest.ServiceReference1.IFileDigger>, FileDiggerTest.ServiceReference1.IFileDigger {
        
        public FileDiggerClient() {
        }
        
        public FileDiggerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileDiggerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDiggerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDiggerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addPeer(string peer) {
            base.Channel.addPeer(peer);
        }
        
        public void deletePeer(string peer) {
            base.Channel.deletePeer(peer);
        }
        
        public string[] findPeers() {
            return base.Channel.findPeers();
        }
        
        public void addFolder(string folder) {
            base.Channel.addFolder(folder);
        }
        
        public void deleteSharedFolder(string folder) {
            base.Channel.deleteSharedFolder(folder);
        }
        
        public string[] findFile(string name) {
            return base.Channel.findFile(name);
        }
        
        public string[] findSharedFolders() {
            return base.Channel.findSharedFolders();
        }
        
        public byte[] fetchFile(string fullName, int i) {
            return base.Channel.fetchFile(fullName, i);
        }
    }
}
