//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileDiggerC.FileDiggerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="FileDiggerService.IFileDigger")]
    public interface IFileDigger {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/ReportLive", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/ReportLiveResponse")]
        void ReportLive(int ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/addFolder", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/addFolderResponse")]
        void addFolder(string folder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/findFile", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/findFileResponse")]
        string[] findFile(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IFileDigger/fetchFile", ReplyAction="http://Microsoft.ServiceModel.Samples/IFileDigger/fetchFileResponse")]
        byte[] fetchFile(string fullName, int i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileDiggerChannel : FileDiggerC.FileDiggerService.IFileDigger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileDiggerClient : System.ServiceModel.ClientBase<FileDiggerC.FileDiggerService.IFileDigger>, FileDiggerC.FileDiggerService.IFileDigger {
        
        public FileDiggerClient() {
        }
        
        public FileDiggerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileDiggerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDiggerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDiggerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ReportLive(int ip) {
            base.Channel.ReportLive(ip);
        }
        
        public void addFolder(string folder) {
            base.Channel.addFolder(folder);
        }
        
        public string[] findFile(string name) {
            return base.Channel.findFile(name);
        }
        
        public byte[] fetchFile(string fullName, int i) {
            return base.Channel.fetchFile(fullName, i);
        }
    }
}
