<?xml version="1.0" encoding="utf-8"?><Database Name="Tracking" Class="TrackingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ANDY-PC\SQLExpress;Initial Catalog=Tracking;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TrackingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tracking" Member="Trackings">
    <Type Name="Tracking">
      <Column Name="wfinstanceid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="wfname" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="currentevent" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="bugid" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>