<?xml version="1.0" encoding="utf-8"?><Database Name="WorkflowInstanceStore" Class="WorkFlowInstanceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ANDY-PC\SQLExpress;Initial Catalog=WorkflowInstanceStore;Integrated Security=True" SettingsObjectName="CommonResource.Properties.Settings" SettingsPropertyName="WorkflowInstanceStoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="[System.Activities.DurableInstancing].InstancesTable" Member="InstancesTables">
    <Type Name="InstancesTable">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="SurrogateInstanceId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SurrogateLockOwnerId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PrimitiveDataProperties" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ComplexDataProperties" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WriteOnlyPrimitiveDataProperties" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WriteOnlyComplexDataProperties" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MetadataProperties" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DataEncodingOption" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MetadataEncodingOption" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Version" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PendingTimer" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WorkflowHostType" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ServiceDeploymentId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SuspensionExceptionName" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="SuspensionReason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BlockingBookmarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastMachineRunOn" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="ExecutionStatus" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Column Name="IsInitialized" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSuspended" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsReadyToRun" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCompleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>