//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Files {
    
    private FilesFile fileField;
    
    private string clsidField;
    
    private bool disabledField;
    
    private bool disabledFieldSpecified;
    
    /// <remarks/>
    public FilesFile File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disabledSpecified {
        get {
            return this.disabledFieldSpecified;
        }
        set {
            this.disabledFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FilesFile {
    
    private FilesFileProperties propertiesField;
    
    private string clsidField;
    
    private string nameField;
    
    private byte imageField;
    
    private string changedField;
    
    private string uidField;
    
    private string descField;
    
    private bool bypassErrorsField;
    
    private bool bypassErrorsFieldSpecified;
    
    private bool userContextField;
    
    private bool userContextFieldSpecified;
    
    private bool removePolicyField;
    
    private bool removePolicyFieldSpecified;
    
    /// <remarks/>
    public FilesFileProperties Properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clsid {
        get {
            return this.clsidField;
        }
        set {
            this.clsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string changed {
        get {
            return this.changedField;
        }
        set {
            this.changedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool bypassErrors {
        get {
            return this.bypassErrorsField;
        }
        set {
            this.bypassErrorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bypassErrorsSpecified {
        get {
            return this.bypassErrorsFieldSpecified;
        }
        set {
            this.bypassErrorsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool userContext {
        get {
            return this.userContextField;
        }
        set {
            this.userContextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userContextSpecified {
        get {
            return this.userContextFieldSpecified;
        }
        set {
            this.userContextFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool removePolicy {
        get {
            return this.removePolicyField;
        }
        set {
            this.removePolicyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool removePolicySpecified {
        get {
            return this.removePolicyFieldSpecified;
        }
        set {
            this.removePolicyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class FilesFileProperties {
    
    private string actionField;
    
    private string fromPathField;
    
    private string targetPathField;
    
    private bool readOnlyField;
    
    private bool readOnlyFieldSpecified;
    
    private bool archiveField;
    
    private bool archiveFieldSpecified;
    
    private bool hiddenField;
    
    private bool hiddenFieldSpecified;
    
    private bool suppressField;
    
    private bool suppressFieldSpecified;
    
    private bool disabledField;
    
    private bool disabledFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fromPath {
        get {
            return this.fromPathField;
        }
        set {
            this.fromPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string targetPath {
        get {
            return this.targetPathField;
        }
        set {
            this.targetPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool readOnly {
        get {
            return this.readOnlyField;
        }
        set {
            this.readOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool readOnlySpecified {
        get {
            return this.readOnlyFieldSpecified;
        }
        set {
            this.readOnlyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool archive {
        get {
            return this.archiveField;
        }
        set {
            this.archiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool archiveSpecified {
        get {
            return this.archiveFieldSpecified;
        }
        set {
            this.archiveFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool hidden {
        get {
            return this.hiddenField;
        }
        set {
            this.hiddenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hiddenSpecified {
        get {
            return this.hiddenFieldSpecified;
        }
        set {
            this.hiddenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool suppress {
        get {
            return this.suppressField;
        }
        set {
            this.suppressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool suppressSpecified {
        get {
            return this.suppressFieldSpecified;
        }
        set {
            this.suppressFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool disabled {
        get {
            return this.disabledField;
        }
        set {
            this.disabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool disabledSpecified {
        get {
            return this.disabledFieldSpecified;
        }
        set {
            this.disabledFieldSpecified = value;
        }
    }
}
